apiVersion: v1
kind: ConfigMap
metadata:
  name: etc-traefik
data:
  traefik.toml: |
    # https://docs.traefik.io/configuration/commons/

    debug = false

    defaultEntryPoints = ["http", "https"]
    
    [entryPoints]
        [entryPoints.http]
        address = ":80"

        [entryPoints.https]
        address = ":443"
          [entryPoints.https.tls]

    [ping]
      entryPoint = "http"

    [acme]
      email = {{ .Values.acmeEmail | quote }}
      storage = "/traefik-acme/acme.json"
      entryPoint = "https"
{{ .Values.acmeDomains | indent 6 }}
      [acme.dnsChallenge]
        provider = {{ .Values.dnsProvider | quote }}

    [accessLog]

    [file]
    
    [backends]
{{ .Values.backends | indent 6 }}

    [frontends]
{{ .Values.frontends | indent 6}}
