apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Namespace }}-traefik
spec:
  storageClassName: {{ .Values.ckanStorageClassName }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
